services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: infradon-postgres-VAP
    environment: 
      POSTGRES_USER: infradon-VAP
      POSTGRES_PASSWORD: banane
      POSTGRES_DB: budget
    ports:
      - "5432:5432"
    volumes:
      - budget_data:/var/lib/postgresql/data

volumes:
  budget_data:
